criaCartao(
'esporte',
'quem é o maior artilheiro da seleção brasileira?',
'Neymar Jr')
criaCartao(
'matemática',
'2+2',
'4')
criaCartao(
'biologia',
'qual',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')