criaCartao(
'esporte',
'quem é o maior artilheiro da seleção brasileira?',
'Neymar Jr')
criaCartao(
'matemática',
'2+2',
'4')
criaCartao(
'biologia',
'qual o alelo dominante',
'AA')
criaCartao(
'música',
'quantas cordas tem uma viola caipira',
'12')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
'categoria',
'pergunta',
'resposta')
criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')
    criaCartao(
    'categoria',
    'pergunta',
    'resposta')